#############################################################################
# Makefile for building: Feedback
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  Feedback.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake VIDEO=VIDEO_ACTIVE -o Makefile Feedback.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -DDEFAULT -DVIDEO_ACTIVE -DDEFAULT -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include/opencv -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Feedback1.0.0
DISTDIR = /home/osboxes/Feedback/.tmp/Feedback1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/local/lib -lopencv_core -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_shape -lopencv_features2d -lopencv_objdetect -lopencv_calib3d -lopencv_contrib -lopencv_legacy -lopencv_flann -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		att_control.cpp \
		feedback.cpp \
		opticalFlow.cpp \
		pid.cpp \
		pos_control.cpp \
		qcustomplot.cpp \
		quadcopter.cpp \
		sensors.cpp \
		serial_port.cpp \
		eulerplot.cpp \
		anglecorrection.cpp moc_mainwindow.cpp \
		moc_qcustomplot.cpp \
		moc_eulerplot.cpp \
		moc_anglecorrection.cpp
OBJECTS       = mainwindow.o \
		att_control.o \
		feedback.o \
		opticalFlow.o \
		pid.o \
		pos_control.o \
		qcustomplot.o \
		quadcopter.o \
		sensors.o \
		serial_port.o \
		eulerplot.o \
		anglecorrection.o \
		moc_mainwindow.o \
		moc_qcustomplot.o \
		moc_eulerplot.o \
		moc_anglecorrection.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Feedback.pro mainwindow.h \
		att_control.h \
		globals.h \
		opticalFlow.h \
		pid.h \
		pos_control.h \
		qcustomplot.h \
		quadcopter.h \
		sensors.h \
		serial_port.h \
		eulerplot.h \
		anglecorrection.h mainwindow.cpp \
		att_control.cpp \
		feedback.cpp \
		opticalFlow.cpp \
		pid.cpp \
		pos_control.cpp \
		qcustomplot.cpp \
		quadcopter.cpp \
		sensors.cpp \
		serial_port.cpp \
		eulerplot.cpp \
		anglecorrection.cpp
QMAKE_TARGET  = Feedback
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Feedback


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_eulerplot.h ui_anglecorrection.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Feedback.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Feedback.pro \
		/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) VIDEO=VIDEO_ACTIVE -o Makefile Feedback.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Feedback.pro:
/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) VIDEO=VIDEO_ACTIVE -o Makefile Feedback.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h att_control.h globals.h opticalFlow.h pid.h pos_control.h qcustomplot.h quadcopter.h sensors.h serial_port.h eulerplot.h anglecorrection.h $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.cpp att_control.cpp feedback.cpp opticalFlow.cpp pid.cpp pos_control.cpp qcustomplot.cpp quadcopter.cpp sensors.cpp serial_port.cpp eulerplot.cpp anglecorrection.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui eulerplot.ui anglecorrection.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) ./Feedback
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_qcustomplot.cpp moc_eulerplot.cpp moc_anglecorrection.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qcustomplot.cpp moc_eulerplot.cpp moc_anglecorrection.cpp
moc_mainwindow.cpp: qcustomplot.h \
		eulerplot.h \
		anglecorrection.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/osboxes/Feedback -I/usr/local/include/opencv -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_qcustomplot.cpp: qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/osboxes/Feedback -I/usr/local/include/opencv -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

moc_eulerplot.cpp: eulerplot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/osboxes/Feedback -I/usr/local/include/opencv -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include eulerplot.h -o moc_eulerplot.cpp

moc_anglecorrection.cpp: anglecorrection.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/osboxes/Feedback -I/usr/local/include/opencv -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include anglecorrection.h -o moc_anglecorrection.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_eulerplot.h ui_anglecorrection.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_eulerplot.h ui_anglecorrection.h
ui_mainwindow.h: mainwindow.ui \
		qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_eulerplot.h: eulerplot.ui \
		qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic eulerplot.ui -o ui_eulerplot.h

ui_anglecorrection.h: anglecorrection.ui \
		qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic anglecorrection.ui -o ui_anglecorrection.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: mainwindow.cpp mainwindow.h \
		qcustomplot.h \
		eulerplot.h \
		anglecorrection.h \
		ui_mainwindow.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

att_control.o: att_control.cpp pid.h \
		att_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o att_control.o att_control.cpp

feedback.o: feedback.cpp sensors.h \
		c_library/common/mavlink.h \
		c_library/common/version.h \
		c_library/common/common.h \
		c_library/protocol.h \
		c_library/mavlink_types.h \
		c_library/mavlink_helpers.h \
		c_library/checksum.h \
		c_library/mavlink_conversions.h \
		c_library/common/mavlink_msg_heartbeat.h \
		c_library/common/mavlink_msg_sys_status.h \
		c_library/common/mavlink_msg_system_time.h \
		c_library/common/mavlink_msg_ping.h \
		c_library/common/mavlink_msg_change_operator_control.h \
		c_library/common/mavlink_msg_change_operator_control_ack.h \
		c_library/common/mavlink_msg_auth_key.h \
		c_library/common/mavlink_msg_set_mode.h \
		c_library/common/mavlink_msg_param_request_read.h \
		c_library/common/mavlink_msg_param_request_list.h \
		c_library/common/mavlink_msg_param_value.h \
		c_library/common/mavlink_msg_param_set.h \
		c_library/common/mavlink_msg_gps_raw_int.h \
		c_library/common/mavlink_msg_gps_status.h \
		c_library/common/mavlink_msg_scaled_imu.h \
		c_library/common/mavlink_msg_raw_imu.h \
		c_library/common/mavlink_msg_raw_pressure.h \
		c_library/common/mavlink_msg_scaled_pressure.h \
		c_library/common/mavlink_msg_attitude.h \
		c_library/common/mavlink_msg_attitude_quaternion.h \
		c_library/common/mavlink_msg_local_position_ned.h \
		c_library/common/mavlink_msg_global_position_int.h \
		c_library/common/mavlink_msg_rc_channels_scaled.h \
		c_library/common/mavlink_msg_rc_channels_raw.h \
		c_library/common/mavlink_msg_servo_output_raw.h \
		c_library/common/mavlink_msg_mission_request_partial_list.h \
		c_library/common/mavlink_msg_mission_write_partial_list.h \
		c_library/common/mavlink_msg_mission_item.h \
		c_library/common/mavlink_msg_mission_request.h \
		c_library/common/mavlink_msg_mission_set_current.h \
		c_library/common/mavlink_msg_mission_current.h \
		c_library/common/mavlink_msg_mission_request_list.h \
		c_library/common/mavlink_msg_mission_count.h \
		c_library/common/mavlink_msg_mission_clear_all.h \
		c_library/common/mavlink_msg_mission_item_reached.h \
		c_library/common/mavlink_msg_mission_ack.h \
		c_library/common/mavlink_msg_set_gps_global_origin.h \
		c_library/common/mavlink_msg_gps_global_origin.h \
		c_library/common/mavlink_msg_param_map_rc.h \
		c_library/common/mavlink_msg_safety_set_allowed_area.h \
		c_library/common/mavlink_msg_safety_allowed_area.h \
		c_library/common/mavlink_msg_attitude_quaternion_cov.h \
		c_library/common/mavlink_msg_nav_controller_output.h \
		c_library/common/mavlink_msg_global_position_int_cov.h \
		c_library/common/mavlink_msg_local_position_ned_cov.h \
		c_library/common/mavlink_msg_rc_channels.h \
		c_library/common/mavlink_msg_request_data_stream.h \
		c_library/common/mavlink_msg_data_stream.h \
		c_library/common/mavlink_msg_manual_control.h \
		c_library/common/mavlink_msg_rc_channels_override.h \
		c_library/common/mavlink_msg_mission_item_int.h \
		c_library/common/mavlink_msg_vfr_hud.h \
		c_library/common/mavlink_msg_command_int.h \
		c_library/common/mavlink_msg_command_long.h \
		c_library/common/mavlink_msg_command_ack.h \
		c_library/common/mavlink_msg_manual_setpoint.h \
		c_library/common/mavlink_msg_set_attitude_target.h \
		c_library/common/mavlink_msg_attitude_target.h \
		c_library/common/mavlink_msg_set_position_target_local_ned.h \
		c_library/common/mavlink_msg_position_target_local_ned.h \
		c_library/common/mavlink_msg_set_position_target_global_int.h \
		c_library/common/mavlink_msg_position_target_global_int.h \
		c_library/common/mavlink_msg_local_position_ned_system_global_offset.h \
		c_library/common/mavlink_msg_hil_state.h \
		c_library/common/mavlink_msg_hil_controls.h \
		c_library/common/mavlink_msg_hil_rc_inputs_raw.h \
		c_library/common/mavlink_msg_optical_flow.h \
		c_library/common/mavlink_msg_global_vision_position_estimate.h \
		c_library/common/mavlink_msg_vision_position_estimate.h \
		c_library/common/mavlink_msg_vision_speed_estimate.h \
		c_library/common/mavlink_msg_vicon_position_estimate.h \
		c_library/common/mavlink_msg_highres_imu.h \
		c_library/common/mavlink_msg_optical_flow_rad.h \
		c_library/common/mavlink_msg_hil_sensor.h \
		c_library/common/mavlink_msg_sim_state.h \
		c_library/common/mavlink_msg_radio_status.h \
		c_library/common/mavlink_msg_file_transfer_protocol.h \
		c_library/common/mavlink_msg_timesync.h \
		c_library/common/mavlink_msg_camera_trigger.h \
		c_library/common/mavlink_msg_hil_gps.h \
		c_library/common/mavlink_msg_hil_optical_flow.h \
		c_library/common/mavlink_msg_hil_state_quaternion.h \
		c_library/common/mavlink_msg_scaled_imu2.h \
		c_library/common/mavlink_msg_log_request_list.h \
		c_library/common/mavlink_msg_log_entry.h \
		c_library/common/mavlink_msg_log_request_data.h \
		c_library/common/mavlink_msg_log_data.h \
		c_library/common/mavlink_msg_log_erase.h \
		c_library/common/mavlink_msg_log_request_end.h \
		c_library/common/mavlink_msg_gps_inject_data.h \
		c_library/common/mavlink_msg_gps2_raw.h \
		c_library/common/mavlink_msg_power_status.h \
		c_library/common/mavlink_msg_serial_control.h \
		c_library/common/mavlink_msg_gps_rtk.h \
		c_library/common/mavlink_msg_gps2_rtk.h \
		c_library/common/mavlink_msg_scaled_imu3.h \
		c_library/common/mavlink_msg_data_transmission_handshake.h \
		c_library/common/mavlink_msg_encapsulated_data.h \
		c_library/common/mavlink_msg_distance_sensor.h \
		c_library/common/mavlink_msg_terrain_request.h \
		c_library/common/mavlink_msg_terrain_data.h \
		c_library/common/mavlink_msg_terrain_check.h \
		c_library/common/mavlink_msg_terrain_report.h \
		c_library/common/mavlink_msg_scaled_pressure2.h \
		c_library/common/mavlink_msg_att_pos_mocap.h \
		c_library/common/mavlink_msg_set_actuator_control_target.h \
		c_library/common/mavlink_msg_actuator_control_target.h \
		c_library/common/mavlink_msg_altitude.h \
		c_library/common/mavlink_msg_resource_request.h \
		c_library/common/mavlink_msg_scaled_pressure3.h \
		c_library/common/mavlink_msg_control_system_state.h \
		c_library/common/mavlink_msg_battery_status.h \
		c_library/common/mavlink_msg_autopilot_version.h \
		c_library/common/mavlink_msg_landing_target.h \
		c_library/common/mavlink_msg_vibration.h \
		c_library/common/mavlink_msg_home_position.h \
		c_library/common/mavlink_msg_set_home_position.h \
		c_library/common/mavlink_msg_message_interval.h \
		c_library/common/mavlink_msg_extended_sys_state.h \
		c_library/common/mavlink_msg_adsb_vehicle.h \
		c_library/common/mavlink_msg_v2_extension.h \
		c_library/common/mavlink_msg_memory_vect.h \
		c_library/common/mavlink_msg_debug_vect.h \
		c_library/common/mavlink_msg_named_value_float.h \
		c_library/common/mavlink_msg_named_value_int.h \
		c_library/common/mavlink_msg_statustext.h \
		c_library/common/mavlink_msg_debug.h \
		c_library/ardupilotmega/mavlink_msg_rangefinder.h \
		serial_port.h \
		opticalFlow.h \
		mainwindow.h \
		qcustomplot.h \
		eulerplot.h \
		anglecorrection.h \
		globals.h \
		quadcopter.h \
		att_control.h \
		pid.h \
		pos_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o feedback.o feedback.cpp

opticalFlow.o: opticalFlow.cpp perspective.cpp \
		globals.h \
		mainwindow.h \
		qcustomplot.h \
		eulerplot.h \
		anglecorrection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opticalFlow.o opticalFlow.cpp

pid.o: pid.cpp pid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pid.o pid.cpp

pos_control.o: pos_control.cpp pid.h \
		pos_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pos_control.o pos_control.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

quadcopter.o: quadcopter.cpp quadcopter.h \
		att_control.h \
		pid.h \
		pos_control.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quadcopter.o quadcopter.cpp

sensors.o: sensors.cpp sensors.h \
		c_library/common/mavlink.h \
		c_library/common/version.h \
		c_library/common/common.h \
		c_library/protocol.h \
		c_library/mavlink_types.h \
		c_library/mavlink_helpers.h \
		c_library/checksum.h \
		c_library/mavlink_conversions.h \
		c_library/common/mavlink_msg_heartbeat.h \
		c_library/common/mavlink_msg_sys_status.h \
		c_library/common/mavlink_msg_system_time.h \
		c_library/common/mavlink_msg_ping.h \
		c_library/common/mavlink_msg_change_operator_control.h \
		c_library/common/mavlink_msg_change_operator_control_ack.h \
		c_library/common/mavlink_msg_auth_key.h \
		c_library/common/mavlink_msg_set_mode.h \
		c_library/common/mavlink_msg_param_request_read.h \
		c_library/common/mavlink_msg_param_request_list.h \
		c_library/common/mavlink_msg_param_value.h \
		c_library/common/mavlink_msg_param_set.h \
		c_library/common/mavlink_msg_gps_raw_int.h \
		c_library/common/mavlink_msg_gps_status.h \
		c_library/common/mavlink_msg_scaled_imu.h \
		c_library/common/mavlink_msg_raw_imu.h \
		c_library/common/mavlink_msg_raw_pressure.h \
		c_library/common/mavlink_msg_scaled_pressure.h \
		c_library/common/mavlink_msg_attitude.h \
		c_library/common/mavlink_msg_attitude_quaternion.h \
		c_library/common/mavlink_msg_local_position_ned.h \
		c_library/common/mavlink_msg_global_position_int.h \
		c_library/common/mavlink_msg_rc_channels_scaled.h \
		c_library/common/mavlink_msg_rc_channels_raw.h \
		c_library/common/mavlink_msg_servo_output_raw.h \
		c_library/common/mavlink_msg_mission_request_partial_list.h \
		c_library/common/mavlink_msg_mission_write_partial_list.h \
		c_library/common/mavlink_msg_mission_item.h \
		c_library/common/mavlink_msg_mission_request.h \
		c_library/common/mavlink_msg_mission_set_current.h \
		c_library/common/mavlink_msg_mission_current.h \
		c_library/common/mavlink_msg_mission_request_list.h \
		c_library/common/mavlink_msg_mission_count.h \
		c_library/common/mavlink_msg_mission_clear_all.h \
		c_library/common/mavlink_msg_mission_item_reached.h \
		c_library/common/mavlink_msg_mission_ack.h \
		c_library/common/mavlink_msg_set_gps_global_origin.h \
		c_library/common/mavlink_msg_gps_global_origin.h \
		c_library/common/mavlink_msg_param_map_rc.h \
		c_library/common/mavlink_msg_safety_set_allowed_area.h \
		c_library/common/mavlink_msg_safety_allowed_area.h \
		c_library/common/mavlink_msg_attitude_quaternion_cov.h \
		c_library/common/mavlink_msg_nav_controller_output.h \
		c_library/common/mavlink_msg_global_position_int_cov.h \
		c_library/common/mavlink_msg_local_position_ned_cov.h \
		c_library/common/mavlink_msg_rc_channels.h \
		c_library/common/mavlink_msg_request_data_stream.h \
		c_library/common/mavlink_msg_data_stream.h \
		c_library/common/mavlink_msg_manual_control.h \
		c_library/common/mavlink_msg_rc_channels_override.h \
		c_library/common/mavlink_msg_mission_item_int.h \
		c_library/common/mavlink_msg_vfr_hud.h \
		c_library/common/mavlink_msg_command_int.h \
		c_library/common/mavlink_msg_command_long.h \
		c_library/common/mavlink_msg_command_ack.h \
		c_library/common/mavlink_msg_manual_setpoint.h \
		c_library/common/mavlink_msg_set_attitude_target.h \
		c_library/common/mavlink_msg_attitude_target.h \
		c_library/common/mavlink_msg_set_position_target_local_ned.h \
		c_library/common/mavlink_msg_position_target_local_ned.h \
		c_library/common/mavlink_msg_set_position_target_global_int.h \
		c_library/common/mavlink_msg_position_target_global_int.h \
		c_library/common/mavlink_msg_local_position_ned_system_global_offset.h \
		c_library/common/mavlink_msg_hil_state.h \
		c_library/common/mavlink_msg_hil_controls.h \
		c_library/common/mavlink_msg_hil_rc_inputs_raw.h \
		c_library/common/mavlink_msg_optical_flow.h \
		c_library/common/mavlink_msg_global_vision_position_estimate.h \
		c_library/common/mavlink_msg_vision_position_estimate.h \
		c_library/common/mavlink_msg_vision_speed_estimate.h \
		c_library/common/mavlink_msg_vicon_position_estimate.h \
		c_library/common/mavlink_msg_highres_imu.h \
		c_library/common/mavlink_msg_optical_flow_rad.h \
		c_library/common/mavlink_msg_hil_sensor.h \
		c_library/common/mavlink_msg_sim_state.h \
		c_library/common/mavlink_msg_radio_status.h \
		c_library/common/mavlink_msg_file_transfer_protocol.h \
		c_library/common/mavlink_msg_timesync.h \
		c_library/common/mavlink_msg_camera_trigger.h \
		c_library/common/mavlink_msg_hil_gps.h \
		c_library/common/mavlink_msg_hil_optical_flow.h \
		c_library/common/mavlink_msg_hil_state_quaternion.h \
		c_library/common/mavlink_msg_scaled_imu2.h \
		c_library/common/mavlink_msg_log_request_list.h \
		c_library/common/mavlink_msg_log_entry.h \
		c_library/common/mavlink_msg_log_request_data.h \
		c_library/common/mavlink_msg_log_data.h \
		c_library/common/mavlink_msg_log_erase.h \
		c_library/common/mavlink_msg_log_request_end.h \
		c_library/common/mavlink_msg_gps_inject_data.h \
		c_library/common/mavlink_msg_gps2_raw.h \
		c_library/common/mavlink_msg_power_status.h \
		c_library/common/mavlink_msg_serial_control.h \
		c_library/common/mavlink_msg_gps_rtk.h \
		c_library/common/mavlink_msg_gps2_rtk.h \
		c_library/common/mavlink_msg_scaled_imu3.h \
		c_library/common/mavlink_msg_data_transmission_handshake.h \
		c_library/common/mavlink_msg_encapsulated_data.h \
		c_library/common/mavlink_msg_distance_sensor.h \
		c_library/common/mavlink_msg_terrain_request.h \
		c_library/common/mavlink_msg_terrain_data.h \
		c_library/common/mavlink_msg_terrain_check.h \
		c_library/common/mavlink_msg_terrain_report.h \
		c_library/common/mavlink_msg_scaled_pressure2.h \
		c_library/common/mavlink_msg_att_pos_mocap.h \
		c_library/common/mavlink_msg_set_actuator_control_target.h \
		c_library/common/mavlink_msg_actuator_control_target.h \
		c_library/common/mavlink_msg_altitude.h \
		c_library/common/mavlink_msg_resource_request.h \
		c_library/common/mavlink_msg_scaled_pressure3.h \
		c_library/common/mavlink_msg_control_system_state.h \
		c_library/common/mavlink_msg_battery_status.h \
		c_library/common/mavlink_msg_autopilot_version.h \
		c_library/common/mavlink_msg_landing_target.h \
		c_library/common/mavlink_msg_vibration.h \
		c_library/common/mavlink_msg_home_position.h \
		c_library/common/mavlink_msg_set_home_position.h \
		c_library/common/mavlink_msg_message_interval.h \
		c_library/common/mavlink_msg_extended_sys_state.h \
		c_library/common/mavlink_msg_adsb_vehicle.h \
		c_library/common/mavlink_msg_v2_extension.h \
		c_library/common/mavlink_msg_memory_vect.h \
		c_library/common/mavlink_msg_debug_vect.h \
		c_library/common/mavlink_msg_named_value_float.h \
		c_library/common/mavlink_msg_named_value_int.h \
		c_library/common/mavlink_msg_statustext.h \
		c_library/common/mavlink_msg_debug.h \
		c_library/ardupilotmega/mavlink_msg_rangefinder.h \
		serial_port.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensors.o sensors.cpp

serial_port.o: serial_port.cpp serial_port.h \
		c_library/common/mavlink.h \
		c_library/common/version.h \
		c_library/common/common.h \
		c_library/protocol.h \
		c_library/mavlink_types.h \
		c_library/mavlink_helpers.h \
		c_library/checksum.h \
		c_library/mavlink_conversions.h \
		c_library/common/mavlink_msg_heartbeat.h \
		c_library/common/mavlink_msg_sys_status.h \
		c_library/common/mavlink_msg_system_time.h \
		c_library/common/mavlink_msg_ping.h \
		c_library/common/mavlink_msg_change_operator_control.h \
		c_library/common/mavlink_msg_change_operator_control_ack.h \
		c_library/common/mavlink_msg_auth_key.h \
		c_library/common/mavlink_msg_set_mode.h \
		c_library/common/mavlink_msg_param_request_read.h \
		c_library/common/mavlink_msg_param_request_list.h \
		c_library/common/mavlink_msg_param_value.h \
		c_library/common/mavlink_msg_param_set.h \
		c_library/common/mavlink_msg_gps_raw_int.h \
		c_library/common/mavlink_msg_gps_status.h \
		c_library/common/mavlink_msg_scaled_imu.h \
		c_library/common/mavlink_msg_raw_imu.h \
		c_library/common/mavlink_msg_raw_pressure.h \
		c_library/common/mavlink_msg_scaled_pressure.h \
		c_library/common/mavlink_msg_attitude.h \
		c_library/common/mavlink_msg_attitude_quaternion.h \
		c_library/common/mavlink_msg_local_position_ned.h \
		c_library/common/mavlink_msg_global_position_int.h \
		c_library/common/mavlink_msg_rc_channels_scaled.h \
		c_library/common/mavlink_msg_rc_channels_raw.h \
		c_library/common/mavlink_msg_servo_output_raw.h \
		c_library/common/mavlink_msg_mission_request_partial_list.h \
		c_library/common/mavlink_msg_mission_write_partial_list.h \
		c_library/common/mavlink_msg_mission_item.h \
		c_library/common/mavlink_msg_mission_request.h \
		c_library/common/mavlink_msg_mission_set_current.h \
		c_library/common/mavlink_msg_mission_current.h \
		c_library/common/mavlink_msg_mission_request_list.h \
		c_library/common/mavlink_msg_mission_count.h \
		c_library/common/mavlink_msg_mission_clear_all.h \
		c_library/common/mavlink_msg_mission_item_reached.h \
		c_library/common/mavlink_msg_mission_ack.h \
		c_library/common/mavlink_msg_set_gps_global_origin.h \
		c_library/common/mavlink_msg_gps_global_origin.h \
		c_library/common/mavlink_msg_param_map_rc.h \
		c_library/common/mavlink_msg_safety_set_allowed_area.h \
		c_library/common/mavlink_msg_safety_allowed_area.h \
		c_library/common/mavlink_msg_attitude_quaternion_cov.h \
		c_library/common/mavlink_msg_nav_controller_output.h \
		c_library/common/mavlink_msg_global_position_int_cov.h \
		c_library/common/mavlink_msg_local_position_ned_cov.h \
		c_library/common/mavlink_msg_rc_channels.h \
		c_library/common/mavlink_msg_request_data_stream.h \
		c_library/common/mavlink_msg_data_stream.h \
		c_library/common/mavlink_msg_manual_control.h \
		c_library/common/mavlink_msg_rc_channels_override.h \
		c_library/common/mavlink_msg_mission_item_int.h \
		c_library/common/mavlink_msg_vfr_hud.h \
		c_library/common/mavlink_msg_command_int.h \
		c_library/common/mavlink_msg_command_long.h \
		c_library/common/mavlink_msg_command_ack.h \
		c_library/common/mavlink_msg_manual_setpoint.h \
		c_library/common/mavlink_msg_set_attitude_target.h \
		c_library/common/mavlink_msg_attitude_target.h \
		c_library/common/mavlink_msg_set_position_target_local_ned.h \
		c_library/common/mavlink_msg_position_target_local_ned.h \
		c_library/common/mavlink_msg_set_position_target_global_int.h \
		c_library/common/mavlink_msg_position_target_global_int.h \
		c_library/common/mavlink_msg_local_position_ned_system_global_offset.h \
		c_library/common/mavlink_msg_hil_state.h \
		c_library/common/mavlink_msg_hil_controls.h \
		c_library/common/mavlink_msg_hil_rc_inputs_raw.h \
		c_library/common/mavlink_msg_optical_flow.h \
		c_library/common/mavlink_msg_global_vision_position_estimate.h \
		c_library/common/mavlink_msg_vision_position_estimate.h \
		c_library/common/mavlink_msg_vision_speed_estimate.h \
		c_library/common/mavlink_msg_vicon_position_estimate.h \
		c_library/common/mavlink_msg_highres_imu.h \
		c_library/common/mavlink_msg_optical_flow_rad.h \
		c_library/common/mavlink_msg_hil_sensor.h \
		c_library/common/mavlink_msg_sim_state.h \
		c_library/common/mavlink_msg_radio_status.h \
		c_library/common/mavlink_msg_file_transfer_protocol.h \
		c_library/common/mavlink_msg_timesync.h \
		c_library/common/mavlink_msg_camera_trigger.h \
		c_library/common/mavlink_msg_hil_gps.h \
		c_library/common/mavlink_msg_hil_optical_flow.h \
		c_library/common/mavlink_msg_hil_state_quaternion.h \
		c_library/common/mavlink_msg_scaled_imu2.h \
		c_library/common/mavlink_msg_log_request_list.h \
		c_library/common/mavlink_msg_log_entry.h \
		c_library/common/mavlink_msg_log_request_data.h \
		c_library/common/mavlink_msg_log_data.h \
		c_library/common/mavlink_msg_log_erase.h \
		c_library/common/mavlink_msg_log_request_end.h \
		c_library/common/mavlink_msg_gps_inject_data.h \
		c_library/common/mavlink_msg_gps2_raw.h \
		c_library/common/mavlink_msg_power_status.h \
		c_library/common/mavlink_msg_serial_control.h \
		c_library/common/mavlink_msg_gps_rtk.h \
		c_library/common/mavlink_msg_gps2_rtk.h \
		c_library/common/mavlink_msg_scaled_imu3.h \
		c_library/common/mavlink_msg_data_transmission_handshake.h \
		c_library/common/mavlink_msg_encapsulated_data.h \
		c_library/common/mavlink_msg_distance_sensor.h \
		c_library/common/mavlink_msg_terrain_request.h \
		c_library/common/mavlink_msg_terrain_data.h \
		c_library/common/mavlink_msg_terrain_check.h \
		c_library/common/mavlink_msg_terrain_report.h \
		c_library/common/mavlink_msg_scaled_pressure2.h \
		c_library/common/mavlink_msg_att_pos_mocap.h \
		c_library/common/mavlink_msg_set_actuator_control_target.h \
		c_library/common/mavlink_msg_actuator_control_target.h \
		c_library/common/mavlink_msg_altitude.h \
		c_library/common/mavlink_msg_resource_request.h \
		c_library/common/mavlink_msg_scaled_pressure3.h \
		c_library/common/mavlink_msg_control_system_state.h \
		c_library/common/mavlink_msg_battery_status.h \
		c_library/common/mavlink_msg_autopilot_version.h \
		c_library/common/mavlink_msg_landing_target.h \
		c_library/common/mavlink_msg_vibration.h \
		c_library/common/mavlink_msg_home_position.h \
		c_library/common/mavlink_msg_set_home_position.h \
		c_library/common/mavlink_msg_message_interval.h \
		c_library/common/mavlink_msg_extended_sys_state.h \
		c_library/common/mavlink_msg_adsb_vehicle.h \
		c_library/common/mavlink_msg_v2_extension.h \
		c_library/common/mavlink_msg_memory_vect.h \
		c_library/common/mavlink_msg_debug_vect.h \
		c_library/common/mavlink_msg_named_value_float.h \
		c_library/common/mavlink_msg_named_value_int.h \
		c_library/common/mavlink_msg_statustext.h \
		c_library/common/mavlink_msg_debug.h \
		c_library/ardupilotmega/mavlink_msg_rangefinder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial_port.o serial_port.cpp

eulerplot.o: eulerplot.cpp eulerplot.h \
		ui_eulerplot.h \
		qcustomplot.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eulerplot.o eulerplot.cpp

anglecorrection.o: anglecorrection.cpp anglecorrection.h \
		ui_anglecorrection.h \
		qcustomplot.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o anglecorrection.o anglecorrection.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_eulerplot.o: moc_eulerplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eulerplot.o moc_eulerplot.cpp

moc_anglecorrection.o: moc_anglecorrection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_anglecorrection.o moc_anglecorrection.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

